### ISSUE TITLE
Private repository access?

### ISSUE THREAD

**Issue by afirth** [plan3/stoneboard#47]
## Situation
oauth2 client/secret created in either org or user
org-owned repo selected in frontend

## Expected outcome
can see milestones

## Actual outcome
Appears to be 404 (github unauthorized)
```
2021-11-17T17:53:08.350261+00:00 app[web.1]: Caused by: java.io.FileNotFoundException: https://api.github.com/repos/FATMAP/aws-dns-zones
2021-11-17T17:53:08.350261+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1893) ~[na:1.8.0_312-heroku]
2021-11-17T17:53:08.350261+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495) ~[na:1.8.0_312-heroku]
2021-11-17T17:53:08.350261+00:00 app[web.1]: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_312-heroku]
2021-11-17T17:53:08.350262+00:00 app[web.1]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[na:1.8.0_312-heroku]
2021-11-17T17:53:08.350262+00:00 app[web.1]: 	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:69) ~[github-api-1.111.jar!/:na]
2021-11-17T17:53:08.350262+00:00 app[web.1]: 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:348) ~[github-api-1.111.jar!/:na]
2021-11-17T17:53:08.350262+00:00 app[web.1]: 	... 108 common frames omitted
2021-11-17T17:53:08.350263+00:00 app[web.1]: 
2021-11-17T17:53:08.357167+00:00 heroku[router]: at=info method=GET path="/milestones/[redacted]/aws-dns-zones" host=sre-stoneboard.herokuapp.com request_id=c89dc471-77a5-473b-8924-356f93aff6b6 fwd="94.139.27.210" dyno=web.1 connect=0ms service=231ms status=500 bytes=701 protocol=https
```

## More info

If I use a public repo, it works fine. I guess that the oauth callback needs to request additional scopes, probably by first getting the orgs and then prompting the user to select which, if any, orgs to grant access to.

## Additional question

If/when I get this working, can I see milestones from multiple repos at once? Project + talk really resonates with me, thanks for the hard work

**Comment by chids** [comment]
You're absolutely right, I probably b0rked this when rewriting in Spring 🤷 Thanks for reporting, sorry for the slow reply - fix inbound!
